#ifdef LSN_USE_WINDOWS

/**
 * Copyright L. Spiro 2022
 *
 * Written by: Shawn (L. Spiro) Wilcoxen
 *
 * Description: Macros useful for making consistent layouts.
 */

#pragma once

#define MW_MENU_TXT( ENC_STR, ENC_LEN )	reinterpret_cast<LPCWSTR>(ENC_STR), ENC_LEN

#ifndef LSN_MAIN_WINDOW_W
#define LSN_MAIN_WINDOW_W				(256 * 1)
#endif	// LSN_MAIN_WINDOW_W

#ifndef LSN_MAIN_WINDOW_H
#define LSN_MAIN_WINDOW_H				(240 * 1)
#endif	// LSN_MAIN_WINDOW_H

#ifndef LSN_LOCK_LEFT
#define LSN_LOCK_LEFT					"??::SL+(??::P::L-??::P::SL)", 0
#endif	// LSN_LOCK_LEFT

#ifndef LSN_LOCK_RIGHT
#define LSN_LOCK_RIGHT					"??::SR+(??::P::R-??::P::SR)", 0
#endif	// LSN_LOCK_RIGHT

#ifndef LSN_LOCK_TOP
#define LSN_LOCK_TOP					"??::ST+(??::P::T-??::P::ST)", 0
#endif	// LSN_LOCK_TOP

#ifndef LSN_LOCK_BOTTOM
#define LSN_LOCK_BOTTOM					"??::SB+(??::P::B-??::P::SB)", 0
#endif	// LSN_LOCK_BOTTOM

#ifndef LSN_LOCK_CENTER_H
#define LSN_LOCK_CENTER_H				"??::P::CL+(??::P::CW>>1)", 0
#endif	// LSN_LOCK_CENTER_H

#ifndef LSN_FIXED_WIDTH
#define LSN_FIXED_WIDTH					"??::W", 0
#endif	// LSN_FIXED_WIDTH

#ifndef LSN_FIXED_HEIGHT
#define LSN_FIXED_HEIGHT				"??::H", 0
#endif	// LSN_FIXED_WIDTH

#ifndef LSN_PARENT_CLEFT
#define LSN_PARENT_CLEFT				"??::P::CL", 0
#endif	// LSN_PARENT_CLEFT

#ifndef LSN_PARENT_CRIGHT
#define LSN_PARENT_CRIGHT				"??::P::CR", 0
#endif	// LSN_PARENT_CRIGHT

#ifndef LSN_PARENT_CTOP
#define LSN_PARENT_CTOP					"??::P::CT", 0
#endif	// LSN_PARENT_CTOP

#ifndef LSN_PARENT_CBOTTOM
#define LSN_PARENT_CBOTTOM				"??::P::CB", 0
#endif	// LSN_PARENT_CBOTTOM

#ifndef LSN_PARENT_CWIDTH
#define LSN_PARENT_CWIDTH				"??::P::CW", 0
#endif	// LSN_PARENT_CWIDTH

#ifndef LSN_PARENT_CHEIGHT
#define LSN_PARENT_CHEIGHT				"??::P::CH", 0
#endif	// LSN_PARENT_CHEIGHT

#ifndef LSN_PARENT_VCLEFT
#define LSN_PARENT_VCLEFT				"??::P::VCL", 0
#endif	// LSN_PARENT_VCLEFT

#ifndef LSN_PARENT_VCRIGHT
#define LSN_PARENT_VCRIGHT				"??::P::VCR", 0
#endif	// LSN_PARENT_VCRIGHT

#ifndef LSN_PARENT_VCTOP
#define LSN_PARENT_VCTOP				"??::P::VCT", 0
#endif	// LSN_PARENT_VCTOP

#ifndef LSN_PARENT_VCBOTTOM
#define LSN_PARENT_VCBOTTOM				"??::P::VCB", 0
#endif	// LSN_PARENT_VCBOTTOM

#ifndef LSN_PARENT_VCWIDTH
#define LSN_PARENT_VCWIDTH				"??::P::VCW", 0
#endif	// LSN_PARENT_VCWIDTH

#ifndef LSN_PARENT_VCHEIGHT
#define LSN_PARENT_VCHEIGHT				"??::P::VCH", 0
#endif	// LSN_PARENT_VCHEIGHT

#ifndef LSN_TOP_VCOFFSET
#define LSN_TOP_VCOFFSET				"??::P::VCT+??::SCT", 0
#endif	// LSN_TOP_VCOFFSET

#ifndef LSN_CHECKSTYLE
#define LSN_CHECKSTYLE					WS_CHILDWINDOW | WS_VISIBLE | WS_TABSTOP | BS_AUTOCHECKBOX
#endif	// LSN_CHECKSTYLE

#ifndef LSN_RADIOSTYLE
#define LSN_RADIOSTYLE					WS_CHILDWINDOW | WS_VISIBLE | WS_TABSTOP | BS_AUTORADIOBUTTON
#endif	// LSN_RADIOSTYLE

#ifndef LSN_STATICSTYLE
#define LSN_STATICSTYLE					WS_CHILDWINDOW | WS_VISIBLE | SS_LEFT
#endif	// LSN_STATICSTYLE

#ifndef LSN_BUTTONSTYLE
#define LSN_BUTTONSTYLE					WS_CHILDWINDOW | WS_VISIBLE | WS_TABSTOP | BS_PUSHBUTTON | BS_TEXT
#endif	// LSN_BUTTONSTYLE

#ifndef LSN_DEFBUTTONSTYLE
#define LSN_DEFBUTTONSTYLE				WS_CHILDWINDOW | WS_VISIBLE | WS_TABSTOP | BS_DEFPUSHBUTTON | BS_TEXT
#endif	// LSN_DEFBUTTONSTYLE

#ifndef LSN_GROUPSTYLE
#define LSN_GROUPSTYLE					WS_CHILDWINDOW | WS_VISIBLE | BS_GROUPBOX
#endif	// LSN_GROUPSTYLE

#ifndef LSN_EDITSTYLE
#define LSN_EDITSTYLE					WS_CHILDWINDOW | WS_VISIBLE | WS_TABSTOP | ES_LEFT | ES_AUTOHSCROLL
#endif	// LSN_EDITSTYLE

#ifndef LSN_COMBOSTYLE
#define LSN_COMBOSTYLE					WS_CHILDWINDOW | WS_VISIBLE | WS_TABSTOP | CBS_DROPDOWN | CBS_HASSTRINGS | CBS_AUTOHSCROLL
#endif	// LSN_COMBOSTYLE

#ifndef LSN_COMBOSTYLE_LIST
#define LSN_COMBOSTYLE_LIST				WS_CHILDWINDOW | WS_VISIBLE | WS_TABSTOP | CBS_DROPDOWNLIST | CBS_HASSTRINGS/* | CBS_AUTOHSCROLL*/ | WS_VSCROLL
#endif	// LSN_COMBOSTYLE_LIST

#ifndef LSN_TOOLTIP_STYLE
#define LSN_TOOLTIP_STYLE				WS_POPUP | TTS_NOPREFIX | TTS_BALLOON | TTS_ALWAYSTIP
#endif	// LSN_TOOLTIP_STYLE

#ifndef LSN_UPDOWN_STYLE
#define LSN_UPDOWN_STYLE				WS_CHILDWINDOW | WS_VISIBLE | WS_TABSTOP | UDS_ARROWKEYS | UDS_AUTOBUDDY
#endif	// LSN_UPDOWN_STYLE

#ifndef LSN_TRACKBAR_STYLE
#define LSN_TRACKBAR_STYLE				WS_CHILDWINDOW | WS_VISIBLE | WS_TABSTOP | TBS_AUTOTICKS | TBS_TOOLTIPS | TBS_BOTH
#endif	// LSN_UPDOWN_STYLE

#ifndef LSN_COMBOSTYLEEX_LIST
#define LSN_COMBOSTYLEEX_LIST			0//WS_EX_NOPARENTNOTIFY
#endif	// LSN_COMBOSTYLEEX_LIST

#ifndef LSN_DEF_STATIC_HEIGHT
#define LSN_DEF_STATIC_HEIGHT			8	// Dialog units.
#endif	// LSN_DEF_STATIC_HEIGHT

#ifndef LSN_DEF_STATIC_HEIGHT_PXL
#define LSN_DEF_STATIC_HEIGHT_PXL		15	// Pixels
#endif	// LSN_DEF_STATIC_HEIGHT_PXL

#ifndef LSN_DEF_CHECK_HEIGHT
#define LSN_DEF_CHECK_HEIGHT			9	// Dialog units.
#endif	// LSN_DEF_CHECK_HEIGHT

#ifndef LSN_DEF_CHECK_HEIGHT_PXL
#define LSN_DEF_CHECK_HEIGHT_PXL		17	// Pixels.
#endif	// LSN_DEF_CHECK_HEIGHT_PXL

#ifndef LSN_DEF_RADIO_HEIGHT
#define LSN_DEF_RADIO_HEIGHT			9	// Dialog units.
#endif	// LSN_DEF_RADIO_HEIGHT

#ifndef LSN_DEF_RADIO_HEIGHT_PXL
#define LSN_DEF_RADIO_HEIGHT_PXL		17	// Pixels.
#endif	// LSN_DEF_RADIO_HEIGHT_PXL

#ifndef LSN_DEF_EDIT_HEIGHT
#define LSN_DEF_EDIT_HEIGHT				12	// Dialog units.
#endif	// LSN_DEF_EDIT_HEIGHT

#ifndef LSN_DEF_EDIT_HEIGHT_PXL
#define LSN_DEF_EDIT_HEIGHT_PXL			23	// Pixels.
#endif	// LSN_DEF_EDIT_HEIGHT_PXL

#ifndef LSN_DEF_COMBO_HEIGHT
#define LSN_DEF_COMBO_HEIGHT			12	// Dialog units.
#endif	// LSN_DEF_COMBO_HEIGHT

#ifndef LSN_DEF_COMBO_HEIGHT_PXL
#define LSN_DEF_COMBO_HEIGHT_PXL		23	// Pixels.
#endif	// LSN_DEF_COMBO_HEIGHT_PXL

#ifndef LSN_DEF_BUTTON_HEIGHT
#define LSN_DEF_BUTTON_HEIGHT			12	// Dialog units.
#endif	// LSN_DEF_BUTTON_HEIGHT

#ifndef LSN_DEF_BUTTON_HEIGHT_PXL
#define LSN_DEF_BUTTON_HEIGHT_PXL		23	// Pixels.
#endif	// LSN_DEF_BUTTON_HEIGHT_PXL

#ifndef LSN_DEF_BUTTON_WIDTH
#define LSN_DEF_BUTTON_WIDTH			43	// Dialog units.
#endif	// LSN_DEF_BUTTON_WIDTH

#ifndef LSN_DEF_BUTTON_WIDTH_PXL
#define LSN_DEF_BUTTON_WIDTH_PXL		75	// Pixels.
#endif	// LSN_DEF_BUTTON_WIDTH_PXL

#ifndef LSN_DEF_PROGRESS_BAR_WIDTH
#define LSN_DEF_PROGRESS_BAR_WIDTH		103 // Pixels
#endif	// LSN_DEF_PROGRESS_BAR_WIDTH

#ifndef LSN_DEF_PROGRESS_BAR_WIDTH_PXL
#define LSN_DEF_PROGRESS_BAR_WIDTH_PXL	180 // Pixels
#endif	// LSN_DEF_PROGRESS_BAR_WIDTH_PXL

#ifndef LSN_DEF_PROGRESS_BAR_HEIGHT
#define LSN_DEF_PROGRESS_BAR_HEIGHT		12 // Pixels
#endif	// LSN_DEF_PROGRESS_BAR_HEIGHT

#ifndef LSN_DEF_PROGRESS_BAR_HEIGHT_PXL
#define LSN_DEF_PROGRESS_BAR_HEIGHT_PXL	23 // Pixels
#endif	// LSN_DEF_PROGRESS_BAR_HEIGHT_PXL

#ifndef LSN_DEF_TRACKBAR_HEIGHT
#define LSN_DEF_TRACKBAR_HEIGHT			24	// Dialog units.
#endif	// LSN_DEF_TRACKBAR_HEIGHT

#ifndef LSN_DEF_TRACKBAR_HEIGHT_PXL
#define LSN_DEF_TRACKBAR_HEIGHT_PXL		45	// Pixels.
#endif	// LSN_DEF_TRACKBAR_HEIGHT_PXL

#ifndef LSN_DEF_TRACKBAR_WIDTH
#define LSN_DEF_TRACKBAR_WIDTH			60	// Dialog units.
#endif	// LSN_DEF_TRACKBAR_WIDTH

#ifndef LSN_DEF_TRACKBAR_WIDTH_PXL
#define LSN_DEF_TRACKBAR_WIDTH_PXL		104	// Pixels.
#endif	// LSN_DEF_TRACKBAR_WIDTH_PXL


#ifndef LSN_GROUP_LEFT
#define LSN_GROUP_LEFT					5	// Dialog units.
#endif	// LSN_GROUP_LEFT

#ifndef LSN_GROUP_LEFT_PXL
#define LSN_GROUP_LEFT_PXL				8	// Pixels.
#endif	// LSN_GROUP_LEFT_PXL

#ifndef LSN_GROUP_RIGHT
#define LSN_GROUP_RIGHT					LSN_GROUP_LEFT		// Dialog units.
#endif	// LSN_GROUP_RIGHT

#ifndef LSN_GROUP_RIGHT_PXL
#define LSN_GROUP_RIGHT_PXL				LSN_GROUP_LEFT_PXL	// Pixels.
#endif	// LSN_GROUP_RIGHT_PXL

#ifndef LSN_GROUP_TOP
#define LSN_GROUP_TOP					9	// Dialog units.
#endif	// LSN_GROUP_TOP

#ifndef LSN_GROUP_TOP_PXL
#define LSN_GROUP_TOP_PXL				14	// Pixels.
#endif	// LSN_GROUP_TOP_PXL

#ifndef LSN_GROUP_BOTTOM
#define LSN_GROUP_BOTTOM				4	// Dialog units.
#endif	// LSN_GROUP_BOTTOM

#ifndef LSN_GROUP_BOTTOM_PXL
#define LSN_GROUP_BOTTOM_PXL			11	// Pixels.
#endif	// LSN_GROUP_BOTTOM_PXL

#ifndef LSN_LEFT_JUST
#define LSN_LEFT_JUST					2	// Dialog units.
#endif	// LSN_LEFT_JUST

#ifndef LSN_LEFT_JUST_PXL
#define LSN_LEFT_JUST_PXL				3	// Pixels.
#endif	// LSN_LEFT_JUST_PXL

#ifndef LSN_TOP_JUST
#define LSN_TOP_JUST					2	// Dialog units.
#endif	// LSN_TOP_JUST

#ifndef LSN_TOP_JUST_PXL
#define LSN_TOP_JUST_PXL				3	// Pixels.
#endif	// LSN_TOP_JUST_PXL

#ifndef LSN_CHECK_JUST
#define LSN_CHECK_JUST					1	// Dialog units.
#endif	// LSN_CHECK_JUST

#ifndef LSN_LABEL_JUST
#define LSN_LABEL_JUST					2	// Dialog units.
#endif	// LSN_CHECK_JUST

#ifndef LSN_EVEN_DIVIDE
#define LSN_EVEN_DIVIDE( FULLW, OFFSET, TOTALDIVS, DIV )															\
										(((FULLW) * (DIV)) / (TOTALDIVS) + (OFFSET))
#endif	// LSN_EVEN_DIVIDE

#ifndef LSN_EVEN_DIVIDE_EX
#define LSN_EVEN_DIVIDE_EX( FULLW, OFFSET, TOTALDIVS, DIV, SPACING )												\
										((((FULLW) + (SPACING)) * (DIV)) / (TOTALDIVS) + (OFFSET))
#endif	// LSN_EVEN_DIVIDE_EX

#ifndef LSN_EVEN_DIVIDE_WIDTH_EX
#define LSN_EVEN_DIVIDE_WIDTH_EX( FULLW, OFFSET, TOTALDIVS, DIV, SPACING )											\
										LSN_EVEN_DIVIDE_EX( FULLW, OFFSET, TOTALDIVS, (DIV) + 1, SPACING ) - LSN_EVEN_DIVIDE_EX( FULLW, OFFSET, TOTALDIVS, DIV, SPACING ) - (SPACING)
#endif	// LSN_EVEN_DIVIDE_WIDTH_EX

#endif	// #ifdef LSN_USE_WINDOWS
